### ISSUE TITLE
Import statement repeated!

### ISSUE THREAD

**Issue by bishtanuj** [anshshori2002/Machine-Learning-Projects#1]
https://github.com/anshshori2002/Churn-Modelling-Prediction/blob/17071c231a95733d5f35c6c717c09ce41f566ef9/Churn%20Modelling%20Prediction.ipynb?short_path=e626a7a#L631

**Comment by bishtanuj** [comment]
It is already import at "https://github.com/anshshori2002/Churn-Modelling-Prediction/blob/master/Churn%20Modelling%20Prediction.ipynb?short_path=e626a7a#L58", so no need to import again!

**Comment by bishtanuj** [comment]
![Screenshot 2022-10-31 at 20-16-35 Churn-Modelling-Prediction_Churn Modelling Prediction ipynb at 17071c231a95733d5f35c6c717c09ce41f566ef9 · anshshori2002_Churn-Modelling-Prediction](https://user-images.githubusercontent.com/78249280/199035741-2109f6c9-a3c0-4183-b810-899f7c196368.png)
![Screenshot 2022-10-31 at 20-16-05 Churn-Modelling-Prediction_Churn Modelling Prediction ipynb at 17071c231a95733d5f35c6c717c09ce41f566ef9 · anshshori2002_Churn-Modelling-Prediction](https://user-images.githubusercontent.com/78249280/199035752-d5785463-2b10-42f3-b433-d4d93afa2bc7.png)

**Comment by anshshori2002** [comment]
I have already resolve this issue.
Thank you.
